# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/CoderMSY/MSYSpecs.git'

target 'iOSInterview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Masonry'
pod 'MSYTableView'
pod 'MSYCategory'

  # Pods for iOSInterview

end
